ci: update deployment workflows for API and web
* Separate deployment steps for `api` and `web` applications.
* Ensure `typecheck` runs before validation and testing.
* Adjust conditions for deployment based on application type.

diff --git a/.github/workflows/deploy-preview.yaml b/.github/workflows/deploy-preview.yaml
--- a/.github/workflows/deploy-preview.yaml
+++ b/.github/workflows/deploy-preview.yaml
@@ -67,12 +67,12 @@ jobs:
       - name: build apps
         run: CLOUDFLARE_ENV=preview pnpm build:apps
 
+      - name: typecheck
+        run: pnpm run typecheck
+
       - name: validate openapi
         if: matrix.app == 'api'
         run: pnpm --filter=@ucdjs/api run lint:openapi
-
-      - name: typecheck
-        run: pnpm run typecheck
 
       - name: test api
         if: matrix.app == 'api'
@@ -80,7 +80,7 @@ jobs:
 
       - name: generate api version
         id: api-version
-        if: matrix.app != 'web'
+        if: matrix.app == 'api'
         env:
           HEAD_REF: ${{ github.head_ref }}
           REF_NAME: ${{ github.ref_name }}
@@ -96,24 +96,42 @@ jobs:
           # combine
           echo "version=$CLEAN_BRANCH-$SHORT_SHA" >> "$GITHUB_OUTPUT"
 
-      - name: deploy ${{ matrix.app }}
-        id: deploy
-        if: ${{ github.event.inputs.dry-run != 'true' }}
+      - name: deploy api
+        id: deploy-api
+        if: ${{ github.event.inputs.dry-run != 'true' && matrix.app == 'api' }}
         env:
           API_VERSION: ${{ steps.api-version.outputs.version || 'latest' }}
         uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37 # v3.14.0
         with:
           apiToken: ${{ secrets.CF_API_TOKEN }}
-          workingDirectory: ./apps/${{ matrix.app }}
+          workingDirectory: ./apps/api
           environment: preview
           accountId: ${{ secrets.CF_ACCOUNT_ID }}
           vars: API_VERSION
 
+      # when using @cloudflare/vite-plugin we can't make use of the `environment` option,
+      # and if we use and empty string it will also fail due to multiple environments being defined
+      - name: deploy web
+        id: deploy-web
+        if: ${{ github.event.inputs.dry-run != 'true' && matrix.app == 'web' }}
+        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37 # v3.14.0
+        with:
+          apiToken: ${{ secrets.CF_API_TOKEN }}
+          workingDirectory: ./apps/web
+          accountId: ${{ secrets.CF_ACCOUNT_ID }}
+
       - name: clean deployment url
         id: clean-url
         env:
-          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
+          API_DEPLOYMENT_URL: ${{ steps.deploy-api.outputs.deployment-url }}
+          WEB_DEPLOYMENT_URL: ${{ steps.deploy-web.outputs.deployment-url }}
         run: |
+          DEPLOYMENT_URL="${API_DEPLOYMENT_URL:-${WEB_DEPLOYMENT_URL}}"
+          if [ -z "$DEPLOYMENT_URL" ]; then
+            echo "No deployment URL found."
+            exit 1
+          fi
+
           CLEANED_URL=$(echo "$DEPLOYMENT_URL" | sed 's/ (custom domain)//')
           echo "deployment-url=https://$CLEANED_URL" >> "$GITHUB_OUTPUT"
 
